### ISSUE TITLE
onenote complemento

### ISSUE THREAD

**Issue by chrisHuaman** [Odotocodot/Flow.Launcher.Plugin.OneNote#12]
Flow Launcher version: 1.16.2
OS Version: 19042.1706
IntPtr Length: 8
x64: True

Python Path: 
Node Path: C:\Users\Lenovo\AppData\Roaming\FlowLauncher\Environments\Node.js\Node-v16.18.0\node-v16.18.0-win-x64\node.exe
Date: 09/30/2023 06:16:59
Exception:
OneNote Exception: 
Websites: https://github.com/Odotocodot/Flow.Launcher.Plugin.OneNote
Author: Odotocodot
Version: 1.1.1
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: Nullable object must have a value.
 ---> System.InvalidOperationException: Nullable object must have a value.
   at Flow.Launcher.Plugin.OneNote.ResultCreator.CreateNotebookResult(IOneNoteExtNotebook notebook, List`1 highlightData)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.ToList()
   at Flow.Launcher.Plugin.OneNote.NotebookExplorer.GetNotebooks(String[] searchStrings)
   at Flow.Launcher.Plugin.OneNote.NotebookExplorer.Explore(Query query)
   at Flow.Launcher.Plugin.OneNote.OneNotePlugin.Query(Query query)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 194
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 216
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 216
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass139_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 849
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults(Boolean isReQuery) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 850
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Odotocodot** [comment]
Hi, what was the search query before the crash happened?

**Comment by Odotocodot** [comment]
Closing this due to lack of response.
