### ISSUE TITLE
crash hotkey

### ISSUE THREAD

**Issue by DudkaGame** [Odotocodot/Flow.Launcher.Plugin.OneNote#2]
Flow Launcher version: 1.12.1
OS Version: Microsoft Windows NT 10.0.22621.0
IntPtr Length: 8
x64: True

Python Path: C:\Users\dimap\AppData\Local\FlowLauncher\app-1.12.1\UserData\Environments\Python\PythonEmbeddable-v3.8.9\pythonw.exe
Node Path: 
Date: 02/11/2023 16:14:50
Exception:
OneNote Exception: 
Websites: https://github.com/Odotocodot/Flow.Launcher.Plugin.OneNote
Author: Odotocodot
Version: 1.0.1
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: 0x80042019
 ---> System.Runtime.InteropServices.COMException (0x80042019): 0x80042019
   at Microsoft.Office.Interop.OneNote.ApplicationClass.FindPages(String bstrStartNodeID, String bstrSearchString, String& pbstrHierarchyXmlOut, Boolean fIncludeUnindexedPages, Boolean fDisplay, XMLSchema xsSchema)
   at ScipBe.Common.Office.OneNote.OneNoteProvider.<>c__DisplayClass4_0.<FindPages>b__0(Application oneNote)
   at ScipBe.Common.Office.OneNote.OneNoteProvider.CallOneNoteSafely[T](Func`2 action)
   at ScipBe.Common.Office.OneNote.OneNoteProvider.FindPages(String searchString)
   at Flow.Launcher.Plugin.OneNote.OneNotePlugin.Query(Query query)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 191
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 213
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 213
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass135_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 821
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 822
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Odotocodot** [comment]
What happened before the error popped up?

**Comment by xnhunter** [comment]
Enable Windows Search service.
