### ISSUE TITLE
Crash when searching 

### ISSUE THREAD

**Issue by CroissantDuNord** [Odotocodot/Flow.Launcher.Plugin.OneNote#7]
Working fine but when i search something, the program crash

Flow Launcher version: 1.14.0
OS Version: Microsoft Windows NT 10.0.22621.0
IntPtr Length: 8
x64: True

Python Path: 
Node Path: 
Date: 03/05/2023 21:13:36
Exception:
OneNote Exception: 
Websites: https://github.com/Odotocodot/Flow.Launcher.Plugin.OneNote
Author: Odotocodot
Version: 1.1.0
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: Object reference not set to an instance of an object.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Flow.Launcher.Plugin.OneNote.ResultCreator.CreatePageResult(IOneNotePage page, IOneNoteSection section, IOneNoteNotebook notebook, List`1 highlightingData)
   at Flow.Launcher.Plugin.OneNote.ResultCreator.CreatePageResult(IOneNoteExtPage page, List`1 highlightingData)
   at Flow.Launcher.Plugin.OneNote.OneNotePlugin.<>c__DisplayClass8_0.<Query>b__0(IOneNoteExtPage pg)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at Flow.Launcher.Plugin.OneNote.OneNotePlugin.Query(Query query)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 191
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 213
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 213
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass135_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 839
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 840
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Odotocodot** [comment]
Was this using default search? i.e. `on`?

**Comment by CroissantDuNord** [comment]
![msedge_OFaUIf3Fej](https://user-images.githubusercontent.com/79372025/222988682-6651b2cc-2a54-4138-9e8b-26a76f72fb6e.gif)
Yea, i was using `on`

**Comment by Odotocodot** [comment]
oh wow thank you for the gif! Will get on this.

**Comment by Odotocodot** [comment]
Believe ive found the bug will push a fix soon if all goes right
