### ISSUE TITLE
crash when using arrow keys to navigate query results

### ISSUE THREAD

**Issue by MercShen** [Odotocodot/Flow.Launcher.Plugin.OneNote#9]
[2023-06-02.txt](https://github.com/Odotocodot/Flow.Launcher.Plugin.OneNote/files/11632528/2023-06-02.txt)

Flow Launcher version: 1.15.0
OS Version: 22631.1830
IntPtr Length: 8
x64: True

Python Path: C:\Users\12069\AppData\Roaming\FlowLauncher\Environments\Python\PythonEmbeddable-v3.8.9\pythonw.exe
Node Path: 
Date: 06/02/2023 14:27:50
Exception:
OneNote Exception: 
Websites: https://github.com/Odotocodot/Flow.Launcher.Plugin.OneNote
Author: Odotocodot
Version: 1.1.1
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: Unable to cast COM object of type 'Microsoft.Office.Interop.OneNote.ApplicationClass' to interface type 'Microsoft.Office.Interop.OneNote.IApplication'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{452AC71A-B655-4967-A208-A4CC39DD7949}' failed due to the following error: The RPC server is unavailable. (0x800706BA).
 ---> System.InvalidCastException: Unable to cast COM object of type 'Microsoft.Office.Interop.OneNote.ApplicationClass' to interface type 'Microsoft.Office.Interop.OneNote.IApplication'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{452AC71A-B655-4967-A208-A4CC39DD7949}' failed due to the following error: The RPC server is unavailable. (0x800706BA).
   at System.StubHelpers.StubHelpers.GetCOMIPFromRCW(Object objSrc, IntPtr pCPCMD, IntPtr& ppTarget, Boolean& pfNeedsRelease)
   at Microsoft.Office.Interop.OneNote.ApplicationClass.FindPages(String bstrStartNodeID, String bstrSearchString, String& pbstrHierarchyXmlOut, Boolean fIncludeUnindexedPages, Boolean fDisplay, XMLSchema xsSchema)
   at ScipBe.Common.Office.OneNote.OneNoteProvider.<>c__DisplayClass4_0.<FindPages>b__0(Application oneNote)
   at ScipBe.Common.Office.OneNote.OneNoteProvider.CallOneNoteSafely[T](Func`2 action)
   at ScipBe.Common.Office.OneNote.OneNoteProvider.FindPages(String searchString)
   at Flow.Launcher.Plugin.OneNote.OneNotePlugin.Query(Query query)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 194
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 216
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 216
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass135_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 836
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 837
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Odotocodot** [comment]
Hey is this error constant throwing? and were you using the notebook explorer when it happened?

**Comment by MercShen** [comment]
Crashed twice when I first installed flow launcher and tried the plugin, I just tested a few times moments ago, all good now. Prob just because I didn't restart after I installed flow launcher. Nice plugin BTW

**Comment by MercShen** [comment]
Crashed twice since I installed flow launcher and tried the plugin, I just tested a few times moments ago, all good now. Prob just because I didn't restart after I installed flowlaucher.
